//! Generated by tools/gen_mc_blocks.py from the Minecraft 1.20.4
//! vanilla block report. Maps every Java Edition block-state id to the
//! nearest MineRust block. Do not edit by hand; regenerate instead.
//!
//! 1.20.4 has 26644 block states; this table run-length encodes them.

use crate::blocks::Block;

/// Highest block-state id covered by the table (1.20.4 = 26643).
pub const MAX_STATE: u32 = 26643;

/// `(first_state_id, block)` runs, ascending. Look up by finding the last
/// run whose start is <= the queried id (see `block_for_state`).
pub static RUNS: [(u32, Block); 247] = [
    (0, Block::Air), (1, Block::Stone), (8, Block::Grass), (10, Block::Dirt),
    (14, Block::Cobblestone), (15, Block::Planks), (24, Block::Stone), (25, Block::Sapling),
    (39, Block::Stone), (79, Block::Bedrock), (80, Block::Water), (96, Block::Lava),
    (112, Block::Sand), (118, Block::Gravel), (119, Block::Sand), (123, Block::GoldOre),
    (125, Block::IronOre), (127, Block::CoalOre), (129, Block::GoldOre), (130, Block::Log),
    (136, Block::BirchLog), (139, Block::JungleLog), (142, Block::Log),
    (145, Block::CherryLog), (148, Block::Log), (154, Block::Stone), (156, Block::Dirt),
    (159, Block::Stone), (162, Block::Log), (165, Block::BirchLog), (168, Block::JungleLog),
    (171, Block::Log), (174, Block::CherryLog), (177, Block::Log), (186, Block::Stone),
    (189, Block::Log), (195, Block::BirchLog), (198, Block::JungleLog), (201, Block::Log),
    (204, Block::CherryLog), (207, Block::Log), (219, Block::BirchLog),
    (222, Block::JungleLog), (225, Block::Log), (228, Block::CherryLog), (231, Block::Log),
    (237, Block::Leaves), (377, Block::CherryLeaves), (405, Block::Leaves),
    (517, Block::Stone), (519, Block::Glass), (520, Block::IronOre), (522, Block::Stone),
    (535, Block::Sandstone), (538, Block::Stone), (2006, Block::TallGrass),
    (2007, Block::Stone), (2008, Block::TallGrass), (2009, Block::Stone), (2047, Block::Wool),
    (2063, Block::Stone), (2075, Block::FlowerYellow), (2076, Block::Stone),
    (2077, Block::FlowerRed), (2078, Block::Stone), (2081, Block::FlowerRed),
    (2082, Block::Stone), (2094, Block::Tnt), (2096, Block::Stone), (2353, Block::Cobblestone),
    (2354, Block::Obsidian), (2355, Block::Stone), (2873, Block::Spawner),
    (2874, Block::Stone), (2954, Block::Chest), (2978, Block::Stone),
    (4274, Block::DiamondOre), (4276, Block::Stone), (4277, Block::CraftingTable),
    (4278, Block::Stone), (4286, Block::Farmland), (4294, Block::Furnace),
    (4302, Block::Stone), (4654, Block::Ladder), (4662, Block::Stone),
    (5734, Block::RedstoneOre), (5738, Block::Stone), (5772, Block::Snow),
    (5782, Block::Cactus), (5798, Block::Stone), (5799, Block::SugarCane),
    (5815, Block::Stone), (5849, Block::Netherrack), (5850, Block::Stone),
    (5852, Block::Blackstone), (5858, Block::Stone), (5863, Block::Glowstone),
    (5864, Block::Stone), (5945, Block::Glass), (5961, Block::Stone),
    (6544, Block::Cobblestone), (6545, Block::Stone), (6677, Block::Log), (6741, Block::Stone),
    (6779, Block::Glass), (6811, Block::Stone), (6813, Block::Log), (6837, Block::Stone),
    (7269, Block::Dirt), (7271, Block::Stone), (7272, Block::NetherBrick),
    (7385, Block::Stone), (7389, Block::EnchantTable), (7390, Block::Stone),
    (7415, Block::EndStone), (7416, Block::Stone), (7417, Block::RedstoneLamp),
    (7419, Block::Stone), (7431, Block::Sandstone), (7511, Block::IronOre),
    (7513, Block::Chest), (7521, Block::Stone), (8569, Block::Sapling), (8576, Block::Stone),
    (9107, Block::Anvil), (9119, Block::Chest), (9143, Block::Stone), (9224, Block::IronOre),
    (9225, Block::Stone), (9356, Block::Wool), (9372, Block::Glass), (9884, Block::Stone),
    (10364, Block::SlimeBlock), (10365, Block::Air), (10399, Block::Stone),
    (10728, Block::Wool), (10745, Block::Stone), (10746, Block::Snow), (10747, Block::Stone),
    (10751, Block::FlowerRed), (10753, Block::Stone), (10755, Block::TallGrass),
    (10759, Block::Stone), (11079, Block::Sandstone), (11162, Block::Stone),
    (11234, Block::Sandstone), (11246, Block::Stone), (11276, Block::NetherBrick),
    (11282, Block::Stone), (11288, Block::Sandstone), (11300, Block::Stone),
    (11307, Block::Sandstone), (11308, Block::Stone), (11309, Block::Sandstone),
    (11310, Block::Stone), (12410, Block::EndStone), (12414, Block::Stone),
    (12494, Block::EndStone), (12495, Block::Stone), (12513, Block::Dirt),
    (12514, Block::Stone), (12539, Block::Snow), (12543, Block::Stone),
    (12544, Block::Netherrack), (12545, Block::NetherBrick), (12546, Block::Stone),
    (12549, Block::Air), (12550, Block::Stone), (12664, Block::Wool), (12760, Block::Stone),
    (12941, Block::Snow), (12942, Block::Stone), (12944, Block::Sapling),
    (12945, Block::Stone), (12958, Block::Air), (12960, Block::Water), (12962, Block::Stone),
    (13042, Block::Sandstone), (13122, Block::Stone), (13362, Block::EndStone),
    (13442, Block::Stone), (13522, Block::Sandstone), (13602, Block::Stone),
    (13842, Block::NetherBrick), (13922, Block::Stone), (14088, Block::Sandstone),
    (14094, Block::Stone), (14112, Block::EndStone), (14118, Block::Sandstone),
    (14124, Block::Stone), (14142, Block::NetherBrick), (14148, Block::Stone),
    (14808, Block::Sandstone), (15132, Block::Stone), (16428, Block::NetherBrick),
    (16752, Block::Stone), (17076, Block::NetherBrick), (17400, Block::Sandstone),
    (17724, Block::EndStone), (18048, Block::Stone), (18420, Block::Smoker),
    (18428, Block::BlastFurnace), (18436, Block::Stone), (18438, Block::Grindstone),
    (18450, Block::Stone), (18466, Block::SmithingTable), (18467, Block::Stone),
    (18579, Block::CrimsonStem), (18591, Block::Stone), (18593, Block::Netherrack),
    (18594, Block::Stone), (18596, Block::CrimsonStem), (18608, Block::Stone),
    (18610, Block::Shroomlight), (18611, Block::Stone), (18666, Block::Planks),
    (18668, Block::Stone), (19372, Block::Composter), (19381, Block::Stone),
    (19445, Block::SlimeBlock), (19446, Block::Stone), (19449, Block::Obsidian),
    (19450, Block::Stone), (19460, Block::Blackstone), (20722, Block::NetherBrick),
    (20724, Block::Stone), (21031, Block::Amethyst), (21081, Block::Stone),
    (22317, Block::Glass), (22318, Block::Snow), (22319, Block::SculkSensor),
    (22415, Block::Stone), (22799, Block::SculkBlock), (22938, Block::Stone),
    (22942, Block::CopperOre), (22944, Block::Stone), (24824, Block::Sapling),
    (24826, Block::Wool), (24827, Block::Stone), (24876, Block::Log), (24884, Block::Stone),
    (24902, Block::Dirt), (24904, Block::Deepslate), (26557, Block::Blackstone),
    (26558, Block::Stone), (26573, Block::Deepslate), (26574, Block::Stone),
];

/// The MineRust block that best approximates Minecraft block-state `id`.
pub fn block_for_state(id: u32) -> Block {
    if id > MAX_STATE {
        return Block::Stone;
    }
    // Binary search for the last run starting at or before `id`.
    let mut lo = 0usize;
    let mut hi = RUNS.len();
    while lo + 1 < hi {
        let mid = (lo + hi) / 2;
        if RUNS[mid].0 <= id {
            lo = mid;
        } else {
            hi = mid;
        }
    }
    RUNS[lo].1
}
